apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: green
  name: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - image: tsubasaxzzz/signal
          name: signal
          args:
            - "-d"
            - "10"
            - "-t"
            - "0"
          imagePullPolicy: Always
          #lifecycle:
          #preStop:
          #exec:
          #command: ["sh", "-c", "sleep 10;"]
#      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: signal
  name: signal
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: green
  type: LoadBalancer
